name: CI/CD

on: [push, pull_request, workflow_dispatch]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          pip install flake8
          pip install black

      - name: Lint with Flake8 and Black
        run: |
          flake8 Bottle.py
          black --check Bottle.py

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.11, 3.8]
    needs: [lint]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: pip install bottle pytest
      - name: Run tests
        run: pytest --doctest-modules --ignore=Bottle.py

  deploy:
    runs-on: ubuntu-latest
    needs: [test]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Display message
        run: echo "Deployment in progress..."

      - name: Check if server is up
        run: |
          curl -Is http://localhost:8000/ | head -n 1

  notification:
    runs-on: ubuntu-latest
    needs: [deploy]
    if: always()
    steps:
      - name: Notify Slack
        run: echo "Slack message"

  coverage:
    runs-on: ubuntu-latest
    needs: [test]
    strategy:
      matrix:
        python-version: [3.11, 3.8]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Generate coverage
        run: |
          pip install pytest
          pip install pytest-cov
          pytest --cov=. . --doctest-modules --ignore=Bottle.py
      - name: Generate coverage badge
        run: coverage-badge -o coverage.svg
      - name: Commit coverage files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add coverage.svg
          git commit -m "Add coverage badge"
          git push
      - name: Update README
        run: |
          echo "[![Coverage](coverage.svg)](./coverage.svg)" >> README.md
          git add README.md
          git commit -m "Add coverage badge to README"
          git push
